// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    if (window.app == null) {
      window.app = {};
    }
    return new app.appView();
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
