// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  if (window.app == null) {
    window.app = {};
  }

  app = window.app;

  app.Task = Backbone.Model.extend({
    defaults: {
      title: '',
      completed: false
    },
    toggle: function() {
      return this.save({
        completed: !this.get('completed')
      });
    }
  });

}).call(this);

/*
//@ sourceMappingURL=task.map
*/
